ActsAsTaggableOn::Tag.create!([
  {name: "adult"},
  {name: "art"},
  {name: "bachelor"},
  {name: "bacholr"},
  {name: "beer"},
  {name: "boat"},
  {name: "boys"},
  {name: "business"},
  {name: "chic"},
  {name: "children"},
  {name: "chocolate"},
  {name: "couple"},
  {name: "dance"},
  {name: "drink"},
  {name: "entertainment"},
  {name: "Family"},
  {name: "food"},
  {name: "fun"},
  {name: "group"},
  {name: "high cost"},
  {name: "history"},
  {name: "honeymoon"},
  {name: "jewelry"},
  {name: "landmark"},
  {name: "leisure"},
  {name: "low cost"},
  {name: "luxury"},
  {name: "massage"},
  {name: "medium cost"},
  {name: "museum"},
  {name: "music"},
  {name: "nightlife"},
  {name: "outdoor"},
  {name: "outdoors"},
  {name: "oysters"},
  {name: "paris"},
  {name: "Park"},
  {name: "rapchandus"},
  {name: "romance"},
  {name: "romantic"},
  {name: "romantic walk"},
  {name: "shopping"},
  {name: "spa"},
  {name: "sport"},
  {name: "stadium"},
  {name: "tourist"},
  {name: "travel"},
  {name: "trendy"},
  {name: "view"},
  {name: "walking"},
  {name: "wine"},
  {name: "yatch"}
])
ActsAsTaggableOn::Tagging.create!([
  {tag_id: 5, taggable_id: 2, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 2, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 2, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 2, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 3, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 3, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 3, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 5, taggable_id: 3, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 4, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 4, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 4, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 9, taggable_id: 4, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 4, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 15, taggable_id: 6, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 16, taggable_id: 6, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 17, taggable_id: 7, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 7, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 8, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 9, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 9, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 9, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 5, taggable_id: 9, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 11, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 13, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 15, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 17, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 54, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 54, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 54, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 54, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 54, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 32, taggable_id: 53, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 33, taggable_id: 53, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 26, taggable_id: 53, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 53, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 53, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 32, taggable_id: 52, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 33, taggable_id: 52, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 52, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 52, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 51, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 51, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 51, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 51, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 34, taggable_id: 62, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 62, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 62, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 35, taggable_id: 62, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 36, taggable_id: 62, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 26, taggable_id: 50, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 50, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 37, taggable_id: 50, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 50, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 50, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 50, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 24, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 26, taggable_id: 24, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 24, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 24, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 63, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 63, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 26, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 26, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 26, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 21, taggable_id: 26, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 26, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 26, taggable_id: 26, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 28, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 17, taggable_id: 28, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 28, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 28, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 28, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 28, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 28, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 64, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 64, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 30, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 30, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 30, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 30, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 64, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 29, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 32, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 38, taggable_id: 32, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 32, taggable_id: 32, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 32, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 32, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 34, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 34, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 34, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 34, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 34, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 65, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 65, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 65, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 35, taggable_id: 48, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 39, taggable_id: 48, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 48, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 48, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 35, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 35, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 35, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 35, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 35, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 35, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 17, taggable_id: 66, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 66, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 66, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 36, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 36, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 38, taggable_id: 36, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 32, taggable_id: 36, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 36, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 36, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 45, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 45, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 45, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 45, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 45, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 45, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 15, taggable_id: 67, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 67, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 67, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 42, taggable_id: 67, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 67, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 43, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 43, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 43, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 43, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 43, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 21, taggable_id: 43, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 43, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 40, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 40, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 18, taggable_id: 40, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 21, taggable_id: 40, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 43, taggable_id: 40, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 26, taggable_id: 40, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 38, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 38, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 44, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 44, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 44, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 45, taggable_id: 44, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 37, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 37, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 37, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 68, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 68, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 34, taggable_id: 68, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 68, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 69, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 46, taggable_id: 69, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 69, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 70, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 70, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 1, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 1, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 11, taggable_id: 1, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 1, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 2, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 3, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 6, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 4, taggable_id: 6, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 23, taggable_id: 13, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 11, taggable_id: 13, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 12, taggable_id: 13, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 7, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 7, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 7, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 7, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 8, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 8, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 8, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 8, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 12, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 12, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 12, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 12, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 15, taggable_id: 14, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 14, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 14, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 28, taggable_id: 14, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 16, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 14, taggable_id: 16, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 25, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 25, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 16, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 48, taggable_id: 31, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 31, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 2, taggable_id: 15, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 15, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 13, taggable_id: 15, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 10, taggable_id: 15, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 48, taggable_id: 55, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 55, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 8, taggable_id: 38, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 48, taggable_id: 57, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 57, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 48, taggable_id: 56, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 56, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 50, taggable_id: 59, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 51, taggable_id: 59, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 60, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 60, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 52, taggable_id: 60, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 59, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 50, taggable_id: 61, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 47, taggable_id: 61, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 6, taggable_id: 61, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 10, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 10, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 33, taggable_id: 10, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 10, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 1, taggable_id: 17, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 17, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 33, taggable_id: 17, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 17, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 33, taggable_id: 29, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 29, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 29, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 54, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 33, taggable_id: 5, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 24, taggable_id: 5, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 51, taggable_id: 5, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 5, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 33, taggable_id: 16, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 7, taggable_id: 16, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 27, taggable_id: 16, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"},
  {tag_id: 55, taggable_id: 58, taggable_type: "Place", tagger_id: nil, tagger_type: nil, context: "tags"}
])
Place.create!([
  {name: "Eiffel Tower", place_type: "Tourist", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Empire State Building", place_type: "Business", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Cipriani Downtown", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Le Baron Rouge", place_type: "Food&Drink", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Madison Square Garden", place_type: "Sport", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Spa at the Four Seasons", place_type: "Luxury", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Guggenheim", place_type: "Museum", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "High Line", place_type: "Outdoors", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Masa", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Wicked, Broadway", place_type: "Art&Entertainment", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Colette", place_type: "Shopping", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Comedy Cellar", place_type: "Art&Entertainment", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Arc de Triomphe", place_type: "Tourist", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Sail NYC", place_type: "Luxury", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Liberty Helicopter Tours", place_type: "Luxury", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Wall Street, Walking Tours", place_type: "Business", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Levain Bakery", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Gateway of India", place_type: "Tourist", country: "India", city: "Mumbai", latitude: "12", longitude: "31"},
  {name: "Royal Palace of Amsterdam", place_type: "Tourist", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Paradiso", place_type: "Arts&Entertainment", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Rucker Park", place_type: "Outdoors", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Wynand Fockink", place_type: "Nightlife", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Central Park", place_type: "Outdoors", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Twee Zwaantjes", place_type: "Nightlife", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Museum of Modern Art", place_type: "Museum", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "9/11 Memorial", place_type: "Tourist", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Max Brenner", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Erotic Museum (Red Light District)", place_type: "Adult", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Columbus Circle", place_type: "Tourist", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Kantjil & de Tijger", place_type: "Food&Drink", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Statue of Liberty", place_type: "Tourist", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Empire State Building", place_type: "Tourist", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Times Square", place_type: "Tourist", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Macy's", place_type: "Shopping", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Chipotle", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Quimet i Quimet", place_type: "Food&Drink", country: "Spain", city: "Barcelona", latitude: "", longitude: ""},
  {name: "Brooklyn Bridge", place_type: "Tourist", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Fundaci   Cultural Hostafrancs", place_type: "Arts&Entertainment", country: "Spain", city: "Barcelona", latitude: "", longitude: ""},
  {name: "Blazing Saddles", place_type: "Outdoors", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Food on Foot Tours", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Greenwich Village Walking Tours", place_type: "Tourist", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Minskoff The Theatre", place_type: "Art&Entertainment", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Nectari", place_type: "Food&Drink", country: "Spain", city: "Barcelona", latitude: "", longitude: ""},
  {name: "Museu d'Histrria de Catalunya", place_type: "Museum", country: "Spain", city: "Barcelona", latitude: "", longitude: ""},
  {name: "Hallelujah! Gospel Wednesday", place_type: "Art&Entertainment", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "test", place_type: "a", country: "", city: "", latitude: "", longitude: ""},
  {name: "Yankee Stadium", place_type: "Outdoors", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Picholine", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "M&Ms store", place_type: "Food&Drink", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "The Children's Place", place_type: "Outdoors", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "New York Spa", place_type: "Art&Entertainment", country: "United States of America", city: "New York City", latitude: "", longitude: ""},
  {name: "Bananenbar (Red Light District)", place_type: "Adult", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "The Winston (Red Light District)", place_type: "Nightlife", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Red Light Windows (Red Light District)", place_type: "Adult", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Booze Cruise", place_type: "Luxury", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Blow Karts", place_type: "Outdoors", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Highland Games", place_type: "Outdoors", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Treasure Hunt", place_type: "Nightlife", country: "Netherlands", city: "Amsterdam", latitude: "", longitude: ""},
  {name: "Le Cab", place_type: "Nightlife", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Au Lapin Agile", place_type: "Arts&Entertainment", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Opera Comique", place_type: "Arts&Entertainment", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Wall of \"I Love You\"", place_type: "Tourist", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "The Louvre", place_type: "Museum", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Airship Paris", place_type: "Luxury", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Champs du Elysées", place_type: "Shopping", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "Adelline", place_type: "Shopping", country: "France", city: "Paris", latitude: "", longitude: ""},
  {name: "La Bon Marché", place_type: "Shopping", country: "France", city: "Paris", latitude: "", longitude: ""}
])
